app:
  name: TestBatchJob
  enableHiveSupport: true
  sparkConf:
    spark.sql.adaptive.enabled: "true"
    spark.master: local
    spark.sql.warehouse.dir: ${OUTPUT_PATH}/batch/metastore_batch
  sparkContext:
    description: Integration test
    hadoopConfiguration:
      hive.default.fileformat: delta
      hive.default.fileformat.managed: delta
schemas:
  - id: schema_input
    kind: inline
    format: spark-ddl
    options:
      value: |
        course_id LONG, course_title STRING, url STRING, is_paid BOOLEAN,
        price DOUBLE, num_subscribers INT, num_reviews INT, num_lectures INT,
        level STRING, content_duration DOUBLE, published_timestamp DATE, subject STRING,
        _corrupt_record STRING
  - id: schema_output
    kind: inline
    format: spark-ddl
    options:
      value: |
        course_id LONG, course_title STRING, url STRING, is_paid BOOLEAN,
        price DOUBLE, num_subscribers INT, num_reviews INT, num_lectures INT,
        level STRING, content_duration DOUBLE, published_timestamp DATE, subject STRING,
        load_date DATE
inputs:
  - id: courses
    format: csv
    schema: schema_input
    kind: batch
    subtype: data-source
    options:
      path: ${INPUT_PATH}
      inferSchema: "false"
      header: "true"
      mode: FAILFAST
  - id: courses_mock
    format: mock
    schema: schema_input
    kind: batch
    subtype: data-source
    options:
      fakers: |
        course_id:Number.randomDigit;
        course_title:Book.title;url:Internet.url;price:Commerce.price;num_subscribers:Number.digit;
        num_reviews:Number.digit;num_lectures:Number.digit;
        level:Number.digit;
        subject:Name.title;
        member1:BackToTheFuture.character
        ;
        ;
steps:
  - id: courses
    kind: cache
    options:
      storageLevel: MEMORY_ONLY
  - id: courses_ext
    kind: sql
    options:
      query: |
        select course_id, course_title, url, is_paid, price, num_subscribers, num_reviews, num_lectures,
        level, content_duration, published_timestamp, subject,
        current_date() as load_date from courses
    dq:
      analysis:
        name: courses_ext_analysis
        analyzers:
          compliance:
            instance: price
            predicate: "price > 100"
          completeness:
            column: course_id
          distinctness:
            columns:
              - course_id
          uniqueness:
            columns:
              - course_id
          uniqueValueRatio:
            columns:
              - course_id
          countDistinct:
            columns:
              - course_id
          entropy:
            column: content_duration
          mutualInformation:
            columns:
              - course_title
              - level
          maximum:
            column: num_lectures
          minimum:
            column: num_lectures
          maxLength:
            column: course_title
          minLength:
            column: course_title
          mean:
            column: price
          sum:
            column: num_subscribers
          size:
          dataType:
            column: level
      verification:
        name: courses_ext_dq
        checks:
          - level: error
            description: Basic DQ validation 1
            hasSize:
              op: ">"
              value: 1
          - level: warning
            description: Basic DQ validation 2
            isComplete:
              column: course_id
            isUnique:
              column: course_id
            isContainedIn:
              column: subject
              allowedValues:
                - Business Finance
                - Web Development
            isNonNegative:
              column: price
            isPositive:
              column: content_duration
            isLessThan:
              columnA: num_reviews
              columnB: num_subscribers
            isLessThanOrEqualTo:
              columnA: num_reviews
              columnB: num_subscribers
            isGreaterThan:
              columnA: num_reviews
              columnB: num_subscribers
            isGreaterThanOrEqualTo:
              columnA: num_reviews
              columnB: num_subscribers
            hasPattern:
              column: course_title
              pattern: "[A-Z]+.*"
            containsURL:
              column: url
  - id: courses_ext_analysis
    kind: show
    options:
      numRows: "100"
      truncate: "false"
  - id: courses_ext_dq
    kind: show
    options:
      numRows: "100"
      truncate: "false"
  - id: courses_mock
    kind: show
    options:
      numRows: "100"
      truncate: "false"
  - id: courses_corrupt_records
    kind: sql
    options:
      query: |
        select _corrupt_record, current_date() as load_date
        from courses where _corrupt_record is not null
outputs:
  - id: courses_ext
    format: avro
    mode: overwrite
    kind: batch
    subtype: data-source
    schema: schema_output
    coalesce: 1
    partitionBy:
      - load_date
    options:
      path: ${OUTPUT_PATH}/batch/courses_ext
  - id: courses_mock
    format: csv
    mode: overwrite
    kind: batch
    subtype: data-source
    coalesce: 1
    options:
      path: ${OUTPUT_PATH}/batch/courses_mock
      header: "true"
  - id: courses_corrupt_records
    format: csv
    mode: overwrite
    kind: batch
    subtype: data-source
    coalesce: 1
    partitionBy:
      - load_date
    options:
      path: ${OUTPUT_PATH}/batch/courses_corrupt_records
  - id: courses_ext_dq
    format: csv
    mode: overwrite
    kind: batch
    subtype: data-source
    coalesce: 1
    options:
      header: "true"
      path: ${OUTPUT_PATH}/batch/courses_ext_dq
  - id: courses_ext_analysis
    format: csv
    mode: overwrite
    kind: batch
    subtype: data-source
    coalesce: 1
    options:
      header: "true"
      path: ${OUTPUT_PATH}/batch/courses_ext_analysis
