name: Hoolok CI build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Hoolok build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.11

      - name: Compile
        run: sbt clean compile

      - name: Assembly
        run: sbt 'set assembly / test := {}' assembly

      - name: Unit and Integration tests with coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          sbt coverage test it:test coverageReport coverageAggregate
          sbt coveralls
